typography_spectrum: 0.3296131603419781
color:
  brandStrength: 0.9173500975593925
  lightness: 0.7874897341243923
  saturation: 0.4371870399918407
  rhythmicContrast: 0.5642226424533874
  brandColors:
    - '#3E454C'
    - '#2185C5'
    - '#7ECEFD'
    - '#FFF6E5'
    - '#FF7F66'
layout_spectrum: 0.49923727684654295
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/adbe32a8-f0e9-4e1b-bef1-2905c06799a4.jpg
name: The Sonic Collective
navigation:
  - name: Our Reviewers
    id: 1a97f8d4-c219-4d43-b117-ee1bf7752572
    type: content
  - name: Our Music
    id: 3ecf11e6-d2e4-449d-8973-5ba0f30f0ddc
    type: content
title: Reviewing Music That Count
description: Reviewing Classic Influential Albums
